### ISSUE TITLE
Any clues why pull/20179 fails?

### ISSUE THREAD

**Issue by gmacario** [astrastefania/pandas-sprint-Turin#6]
See https://github.com/pandas-dev/pandas/pull/20179
@astrastefania, @xrmx: Any ideas?

I suspect there is something wrong on pandas-dev CI.
Unfortunately I am not a Python expert (but would like to learn...) so I cannot understand what is wrong.

`<shameless-plug>`

Moreover, I have nearly zero experience on CircleCI - but here I like [Jenkins](https://github.com/gmacario/easy-jenkins) much more!!!

`</shameless-plug>`

**Comment by xrmx** [comment]
@gmacario unrelated to your changes, don't mind that. If you add a comment that you have updated the PR after addressing the review comments may help in getting another review though.

**Comment by gmacario** [comment]
Thank @xrmx - as suggested I also pinged @kynan.

Let us see whether my PR will go through; I also want to have a  :purple_heart: close to my name in https://github.com/astrastefania/pandas-sprint-Turin/blob/master/README.md :wink:

**Comment by xrmx** [comment]
@gmacario you got it!
